# Generated by Django 5.0.1 on 2026-01-13 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_match_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patch', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('league', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analytics.match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='analytics.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='analytics.team'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bans', models.JSONField(default=list)),
                ('picks', models.JSONField(default=list)),
                ('win_probability', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='analytics.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.team')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_pool', to='analytics.player')),
            ],
            options={
                'unique_together': {('player', 'champion')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('vision_score', models.IntegerField(default=0)),
                ('gold_earned', models.IntegerField(default=0)),
                ('positioning_score', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='analytics.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barons', models.IntegerField(default=0)),
                ('dragons', models.IntegerField(default=0)),
                ('towers', models.IntegerField(default=0)),
                ('gold_diff_15', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='analytics.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.team')),
            ],
            options={
                'unique_together': {('match', 'team')},
            },
        ),
    ]
