# Generated by Django 5.0.1 on 2026-01-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auditlog_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='format_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='game_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
